[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook_vault = "B6Ko2vrRgrURt9VEoF4Jq6TVpWTCzJjjEsiGic2tZrPV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
